baseurl = "https://thibmeu.github.io/"
title = "Thibault Meunier"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Thibault Meunier"
    info = "I'm talking to computers to make them work"
    description = "Thibault Meunier's personal website"
    keywords = "blog,developer,personal"

    hidecredits = false
    hidecopyright = true

    colorScheme = "auto"
    hidecolorschemetoggle = false

    math = false

# Social links
[[params.social]]
    name = "Github"
    icon = "fa fa-github fa-2x"
    weight = 1
    url = "https://github.com/thibmeu/"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/thibmeu/"
[[params.social]]
    name = "RSS"
    icon = "fa fa-rss fa-2x"
    weight = 3
    url = "/index.xml"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "posts/"

[[menu.main]]
    name = "Projects"
    weight = 2
    url  = "projects/"

[[menu.main]]
    name = "Links"
    weight = 3
    url  = "links/"
