baseurl = "https://thibault.uk"
title = "Thibault Meunier"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Thibault Meunier"
    info = "I'm talking to computers to make them work"
    description = "Thibault Meunier's personal website"
    keywords = "blog,developer,personal"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    hidecredits = false
    hidecopyright = true

    math = false

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/thibmeu/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/thibmeu/"
[[params.social]]
    name = "RSS"
    icon = "fas fa-rss fa-2x"
    weight = 3
    url = "/posts/index.xml"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
